services:
  postgres:
    container_name: kwitch-postgres
    image: postgres:17.0-alpine3.20
    hostname: ${POSTGRES_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
  
  redis:
    container_name: kwitch-redis
    image: redis:7.4.1-alpine3.20
    hostname: ${REDIS_HOST}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./volumes/redis-data:/var/lib/redis/data
    command:
    - /bin/sh
    - -c
    - redis-server --requirepass "$${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIST_PASSWORD", "--raw", "incr", "ping" ]
  
  api:
    container_name: kwitch-api
    image: sukjuhong/kwitch-api:latest
    hostname: kwitch-api
    ports:
      - "8000:8000"
      - ${MEDIASOUP_WEBRTC_SERVER_PORT}-${MEDIASOUP_WEBRTC_SERVER_PORT_MAX}:${MEDIASOUP_WEBRTC_SERVER_PORT}-${MEDIASOUP_WEBRTC_SERVER_PORT_MAX}/tcp
      - ${MEDIASOUP_WEBRTC_SERVER_PORT}-${MEDIASOUP_WEBRTC_SERVER_PORT_MAX}:${MEDIASOUP_WEBRTC_SERVER_PORT}-${MEDIASOUP_WEBRTC_SERVER_PORT_MAX}/udp
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MEDIASOUP_LISTEN_IP: ${MEDIASOUP_LISTEN_IP}
      MEDIASOUP_ANNOUNCED_IP: ${MEDIASOUP_ANNOUNCED_IP}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    container_name: kwitch-web
    image: sukjuhong/kwitch-web:latest
    hostname: kwitch-web
    ports:
      - "3000:3000"