services:
  postgresql:
    image: postgres:16.4-alpine
    restart: unless-stopped
    container_name: kwitch-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-develop}
      POSTGRES_DB: ${POSTGRES_DB:-kwitch}
    volumes:
      - ../volumes/postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    container_name: kwitch-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10