name: Build Docker image and push to Docker Hub

inputs:
  username:
    description: 'Docker Hub username'
    required: true
  app:
    description: 'application name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./apps/${{ inputs.app }}/Dockerfile
        push: true
        tags: ${{ inputs.username }}/${{ inputs.app }}:latest
