name: Deploy apps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  build-and-push-apps:
    name: Build and push apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        username: [sukjuhong]
        app: [api, web]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          username: ${{ matrix.username }}
          app: ${{ matrix.app }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push-apps]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying..."
