name: Deploy apps

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  generate-apps-matrix:
    name: Generate apps matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: |
          matrix=$(jq -n --arg apps "$(ls apps)" '{
            include: [split(" ") | .[] | {name: ., dockerfile: "apps/\(.)/Dockerfile"}]
          }')
          echo "::set-output name=matrix::$matrix"

  build-and-push-apps:
    name: Build and push apps
    runs-on: ubuntu-latest
    needs: [generate-apps-matrix]
    strategy:
      matrix: ${{fromJson(needs.generate-apps-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push
        with:
          image-tag: ${{ matrix.image-tag }}
          dockerfile: ${{ matrix.dockerfile }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push-apps]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploying..."
